spring:
# 配置数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://139.9.73.191:3306/re?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      validation-query: SELECT 1
      initial-size: 1
      min-idle: 1
      max-active: 20
      filters: stat
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 3000000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      username: root_element
      password: ljtLJT715336
  thymeleaf:
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
    enabled: true
# 配置debug模式
debug: true
#配置mybatis相关
mybatis:
  configuration:
    # 配置打印sql
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 配置服务器相关
server:
  port: 80
  servlet:
    context-path: /re
